name: CI

on:
  push:
    branches:
    - master
    - develop/github/*
    - release/*
  pull_request:
    branches:
    - master

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v5.0.0
      with:
        fetch-depth: 2
    - uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json
        cache: true
        cache-dependency-path: |
          **/*.csproj
          **/*.fsproj
          **/packages.lock.json
    - name: Tools
      run: dotnet tool restore
    - name: Setup
      run: dotnet run --project .\Build\Setup.fsproj
    - name: Build
      env:
#        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        NUGET_API_TOKEN: ${{ secrets.NUGET_API_TOKEN }}
      run: dotnet run --project .\Build\Build.fsproj
    - uses: actions/upload-artifact@v4
      with:
          name: nupkgs
          path: _Packagin*/*.nupkg
